DELETE http://localhost:3003/api/blogs/63d599ead311e9a0203eae75
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJpZCI6IjYzZDU0OWI1MGM0Y2UyNDhkNDYzZTU0ZSIsImlhdCI6MTY3NDk0NTYzNCwiZXhwIjoxNjc0OTQ5MjM0fQ.urAl5BfetZm6it7MfHMTyAZO3zgSfAfpTJL87hkUeO4